__version__ = '0.6.0'

from .apply_along_axes import apply_along_axes

class VorpyException(Exception):
    """
    Base class for some exceptions generated by the vorpy module.  Eventually this will be
    the base class for all exceptions generated by the vorpy module."""
    pass

class VorpyProgrammerError(Exception):
    """Base class for all internal programmer error exceptions generated by the vorpy module."""
    pass
